playerdata = {
    {"Weea-Madoran", "Use of racial slurs against asians"},
    {"Sentinguard-Aegwynn", "intentionally pulling whole dungeon"},
    {"Selkie-Ragnaros", "AFK in mythic while spamming nonsense"},
    {"Griggy-Drak'thul", "joined mythic and left at final boss"},
    {"Feldemonizer-Arthas", "throwing dungeon and being racist"},
    {"Feldemonizer-Arthas", "Excessive toxicity"},
    {"Elysiá-Sargeras", "Excessive toxicity for no good reason"},
	{"Chuknourishs-Anvilmar", "Flaming before leaving dungeon"},
	{"Vizanna-Proudmoore", "Throwing and flaming mythic dungeon"},
	{"Ðottie-Stormrage", "Intentionally leaving mythic halfway"},
	{"Imsoicy-Kel'Thuzad", "Insulting in spanish and throwing dungeon"},
	{"Togå-Stormrage", "Harassing players and part of toxic guild"},
	{"Talvio-Stormrage", "Harassing players and part of toxic guild"},
	{"Adaphegìa-Stormrage", "Harassing players and part of toxic guild"},
	{"Kaelstrasz-Stormrage", "Harassing players and part of toxic guild"},
    {"Dhampirbebe-Darkspear", "acting like a pedophile in trade chat"},
    {"Défteros-Quel'Thalas", "Intentionally ruined a mythic keystone run by throwing and passing aggro onto others three minutes into the run, then left"},
    {"Deaddisiplez-Kil'jaeden", "Ignored mechanics in a mythic plus run and kept overpulling many times despite the group asking him to stop"},
    {"Blàzer-Stormrage", "Making racist comments towards a Chinese player"}
}