playerdata = {
    {"Weea-Madoran", "Use of racial slurs against asians"},
    {"Sentinguard-Aegwynn", "intentionally pulling whole dungeon"},
    {"Selkie-Ragnaros", "AFK in mythic while spamming nonsense"},
    {"Griggy-Drak'thul", "joined mythic and left at final boss"},
    {"Feldemonizer-Arthas", "throwing dungeon and being racist"},
    {"Feldemonizer-Arthas", "Excessive toxicity"},
    {"Elysiá-Sargeras", "Excessive toxicity for no good reason"},
	{"Chuknourishs-Anvilmar", "Flaming before leaving dungeon"},
	{"Vizanna-Proudmoore", "Throwing and flaming mythic dungeon"},
	{"Ðottie-Stormrage", "Intentionally leaving mythic halfway"},
	{"Imsoicy-Kel'Thuzad", "Insulting in spanish and throwing dungeon"},
	{"Togå-Stormrage", "Harassing players and part of toxic guild"},
	{"Talvio-Stormrage", "Harassing players and part of toxic guild"},
	{"Adaphegìa-Stormrage", "Harassing players and part of toxic guild"},
	{"Kaelstrasz-Stormrage", "Harassing players and part of toxic guild"},
    {"Dhampirbebe-Darkspear", "acting like a pedophile in trade chat"},
    {"Défteros-Quel'Thalas", "Intentionally ruined a mythic keystone run by throwing and passing aggro onto others three minutes into the run, then left"},
    {"Deaddisiplez-Kil'jaeden", "Ignored mechanics in a mythic plus run and kept overpulling many times despite the group asking him to stop"},
	{"Lørðærøn-Quel'Thalas", "We wiped in mythic, tank accidentally pulled, then decided to start throwing, then said he didn't have much time to play and left dungeon"},
	{"Harux-Darkspear", "Using homophobic slurs against players questing with them"},
	{"Eisenpower-Proudmoore", "Running ahead in a mog run, pulling all the bosses, and locking everyone out of their loot"},
	{"Khaltath-Frostmourne", "Power tripping raid lead. Pulled without ready check when people were afk, raged in comms, then kicked over half the group"},
	{"Dripshot-Shadowsong", "Leaves groups if he doesn't think you will make time."},
	{"Mylam-Tichondrius", "Was questioned about his tanking, then told the group to f*** off and left 8 mins into a +8"},
	{"Gara-Kel'Thuzad", "Harassing group members after someone left a mythic"},
	{"Äisemberg-Quel'Thalas", "Threw dungeon, insulting players in Spanish"},
	{"Shinymagic-Ysera", "Being toxic and using homophobic slurs in a dungeon"},
	{"Kaarrol-Stormrage", "Locking people out of mog run and kicking them to prevent them from getting loot"},
	{"Thebigbrute-Illidan", "Being racist and homophobic during a battleground"},
	{"Deämerz-Stormrage", "Being racist and homophobic during a battleground"},
	{"Zaniron-Stormrage", "Being racist and homophobic during a battleground"},
	{"Mahwang-Uther", "Got mad at healer so he pulled the whole dungeon and left in a +9"},
	{"Classybtch-Darkspear", "Whispering people calling them btch"},
	{"Háhàháhà-Stormrage", "Being toxic and insulting people in mythics"},
    {"Blàzer-Stormrage", "Making racist comments towards a Chinese player"},
	{"Estefierroté-Ragnaros", "Pulling whole dungeon and then leaving"}
}